# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :rta_host) || "localhost" %>
  database: <%= Rails.application.credentials.dig(:database, :rta_db) || "RailsTestApplication_dev" %>
  username: <%= Rails.application.credentials.dig(:database, :rta_username) || "your_username" %>
  password: <%= Rails.application.credentials.dig(:database, :rta_password) || "your_password" %>

test:
  <<: *default
  database: RailsTestApplication_test
  username: "your_test_username"
  password: "your_test_password"

production:
  primary: &primary_production
    <<: *default
    host: <%= Rails.application.credentials.dig(:database, :rta_host) %>
    database: <%= Rails.application.credentials.dig(:database, :rta_db) %>
    username: <%= Rails.application.credentials.dig(:database, :rta_username) %>
    password: <%= Rails.application.credentials.dig(:database, :rta_password) %>

  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
